spring.application.name=SpringSecurityAuthentication
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true


spring.datasource.url=jdbc:postgresql://localhost:5432/spring-security
spring.datasource.username=postgres
spring.datasource.password=saurav

spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql
#spring.jpa.defer-datasource-initialization=true

       # Spring config
spring.security.user.name=saurav
spring.security.user.password=pass