spring.application.name=LoggingUsingSLF4J

spring.datasource.url=jdbc:postgresql://localhost:5432/auditing
spring.datasource.username=postgres
spring.datasource.password=saurav

spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Set logging level for your package
logging.level.com.codingsrv.LoggingUsingSLF4J=TRACE

# Set log at entire application
logging.level.root=INFO

# Optional: show logs in console with custom pattern
logging.pattern.console=%d{dd-MM-yyyy HH:mm:ss} - [%level] - [%c] - %m%n

#Log Handler(logs are stored in this file)
logging.file.name=application.log

#To set the pattern of the logs in file
logging.pattern.file= %d{dd-MM-yyyy HH:mm:ss} [%level] [%c{1.}]  [%t] %m%n