spring.application.name=SpringTransactionManagement

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true


spring.datasource.url=jdbc:postgresql://localhost:5432/Caching
spring.datasource.username=postgres
spring.datasource.password=saurav

# Redis(localhost)
#spring.data.redis.host=localhost
#spring.data.redis.port=6379

#Redis(Redis cloud)
#spring.cache.type=redis
spring.data.redis.host=redis-15360.crce182.ap-south-1-1.ec2.cloud.redislabs.com
spring.data.redis.port=15360
spring.data.redis.password=o5i6uqZ0C8owvYHH5ubRTsaHr66ARtEv
#spring.data.redis.ssl.enabled=false