spring.application.name=order-service

server.servlet.context-path=/orders
server.port=9002

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/orderDB
spring.datasource.username=postgres
spring.datasource.password=saurav

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-location=classpath:data.sql