spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: hhjhjjkjkkjjk
            client-secret: ggghghhhjhjhjhjh

          github:
            client-id: yweyffywfywe
            client-secret: ywefyfwlfwfuw

          facebook:
            client-id: yweyffywfywefweifwfiwfi
            client-secret: kjksfhefwkdjwkfi


