spring.application.name=SpringBootActuator

spring.datasource.url=jdbc:postgresql://localhost:5432/auditing
spring.datasource.username=postgres
spring.datasource.password=saurav

spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Actuator configuration

#To enable the few endpoints at once
management.endpoints.web.exposure.include=health,info,beans,env

#To enable all the endpoints at once
#management.endpoints.web.exposure.include=*

#We can change the base path from the /actuator to any custom endpoint
#management.endpoints.web.base-path=/management

#To inject custom information inside /info endpoint
management.info.env.enabled=true
info.app.name=MyApplication
info.app.version=1.0
info.abcd=pqrs
