spring.application.name=OpenApiSwaggerDocumentation

spring.datasource.url=jdbc:postgresql://localhost:5432/auditing
spring.datasource.username=postgres
spring.datasource.password=saurav

spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true